# Use an official lightweight Python image.
FROM python:3.10-slim
 
# Prevent Python from writing pyc files and buffer stdout/stderr.
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
 
# Set the working directory in the container.
WORKDIR /app
 
# Install system dependencies.
RUN apt-get update && apt-get install -y
 
# Copy the requirements file and install Python dependencies.
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt --use-deprecated=legacy-resolver
 
# Copy the rest of the project files.
COPY . .
 
# Expose the port your Django app will run on.
EXPOSE 9987
 
# Run the application using gunicorn.
# Replace "myproject" with your Django project name.
CMD ["uvicorn", "biasbracker_server.asgi:application", "--host", "0.0.0.0", "--port", "9987"]