# Generated by Django 5.1.6 on 2025-02-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cognitive_bias',
            field=models.CharField(choices=[('Confirmation Bias', 'Confirmation Bias'), ('Anchoring Bias', 'Anchoring Bias'), ('Availability Bias', 'Availability Bias'), ('Framing Effect', 'Framing Effect'), ('Overconfidence Bias', 'Overconfidence Bias'), ('Negativity Bias', 'Negativity Bias'), ('Bandwagon Effect', 'Bandwagon Effect'), ('Sunk Cost Fallacy', 'Sunk Cost Fallacy')], db_index=True, default='Confirmation Bias', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='perspective',
            field=models.CharField(choices=[('Neutral', 'Neutral'), ('Optimistic', 'Optimistic'), ('Critical', 'Critical'), ('Innovative', 'Innovative'), ('Ethical', 'Ethical')], db_index=True, default='Neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.JSONField(),
        ),
    ]
