# Generated by Django 5.1.6 on 2025-02-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_summary_remove_article_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
