# Generated by Django 5.1.6 on 2025-02-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alternativeperspective_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.CharField(default='General', max_length=255),
        ),
    ]
