# Generated by Django 5.1.6 on 2025-03-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='article_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
